#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

AUTOMX_VERSION="1.1.2"

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	httpd_memory
"

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Setup automx"
curl -L -O https://download.qutic.com/src/automx/automx-${AUTOMX_VERSION}.tar.gz
gtar xf automx-${AUTOMX_VERSION}.tar.gz
rm automx-${AUTOMX_VERSION}.tar.gz

sed -i \
    's#/usr/local/etc/automx.conf#/opt/local/etc/automx.conf#' \
    automx-${AUTOMX_VERSION}/src/automx/config.py

mkdir -p /opt/local/lib/automx
cp automx-${AUTOMX_VERSION}/src/automx_wsgi.py /opt/local/lib/automx/
cp automx-${AUTOMX_VERSION}/src/automx-test /opt/local/bin/automx-test
cp -r automx-${AUTOMX_VERSION}/src/automx /opt/local/lib/python3.12
cp -a automx-${AUTOMX_VERSION}/doc/man/ /opt/local/man
cp automx-${AUTOMX_VERSION}/src/conf/automx.conf /opt/local/etc/
rm -rf automx-${AUTOMX_VERSION}

pip-3.12 install --upgrade pip
pip-3.12 install mysqlclient
pip-3.12 install ipaddr
pip-3.12 install ipaddress

ln -nfs /opt/local/bin/swig4.0 /opt/local/bin/swig
pip-3.12 install m2crypto

touch /var/log/automx.log
chown www:www /var/log/automx.log

ln -nfs /usr/bin/xxd /opt/local/bin/hexdump
sed -i 's/hexdump -C/hexdump/' /opt/local/bin/automx-test

echo "* Enable memcached"
svcadm enable svc:/pkgsrc/memcached:default

# Clean up
echo "* Cleaning up."
rm /root/customize
pkgin -y rm gcc13

# Prepare image for provisioning
sm-prepare-image -y
